# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Node.js image as a base
FROM node:18-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy the source code and tsconfig.json
COPY src ./src
COPY tsconfig.json ./

# Build the project
RUN npm run build

# Use a smaller image for the final release
FROM node:18-alpine AS release

# Set working directory
WORKDIR /app

# Copy the build output from the builder stage
COPY --from=builder /app/build ./build

# Copy the package.json and package-lock.json
COPY --from=builder /app/package.json /app/package-lock.json ./

# Set the API key as an environment variable
ENV SEARCH1API_KEY=YOUR_SEARCH1API_KEY

# Install only production dependencies
RUN npm ci --omit=dev

# Define the command to run the application
ENTRYPOINT ["node", "build/index.js"]